Adding tests about Accordion-Questions and Scooter Order
teserstar/Sprint_4 pull request #1
Opened 2022-09-28 21:22 UTC by teserstar

Добавлены тесты на проверку содержания раздела "Вопросы о важном" и позитивный сценарий заказа самоката.

2022-09-29 19:55 UTC, pavel-ulan requested changes
Неплохо. Есть пара моментов которые надо исправить (посмотри комменты). Плюс мне совсем непонятна твоя любовь к константам, зачем это?

2022-09-29 19:55 UTC, pavel-ulan commented on src/test/java/ru/yandex/practicum/pages/OrderPage.java
> +        System.out.println(orderNumber);
А зачем вывод номера заказа в консоль?

2022-09-29 19:55 UTC, pavel-ulan commented on src/test/java/ru/yandex/practicum/pages/OrderPage.java
> +    private final By logoScooter = By.xpath(".//a[contains(@class, 'LogoScooter')]");
Не совсем понятно для чего ты эти поля делаешь final. Напиши, пожалуйста. т.к. я например не вижу такой необходимости.
Но раз уж ты используешь константы, то будь добр использовать правильно namingConvention. так константы пишутся в UPPER_CASE.

2022-09-29 19:55 UTC, pavel-ulan commented on src/test/java/ru/yandex/practicum/tests/ContentOfAccordionQuestionsTest.java
> +        options.addArguments("--no-sandbox", "--headless", "--disable-dev-shm-usage");
я бы не советовал использовать headless mode без необходимости. могут быть разные результаты с и без визуальной оболочки.

2022-09-29 19:55 UTC, pavel-ulan commented on src/test/java/ru/yandex/practicum/tests/ContentOfAccordionQuestionsTest.java
> +    }
Очень тебя понимаю и согласен, что параметризация тут подходит лучше, но в задании явно указано "Важно написать отдельный тест на каждый вопрос.". А работа с ТЗ - неотъемлемая часть работы тестировщика. Так что исправь пожалуйста.

2022-09-29 19:55 UTC, pavel-ulan commented on src/test/java/ru/yandex/practicum/tests/CreatingScooterOrderTest.java
> +        };
Да, тут уже можно и параметризацию использовать, т.к. отдельного требования не было. 👍

2022-09-30 09:52 UTC, teserstar commented on src/test/java/ru/yandex/practicum/pages/OrderPage.java
> +        System.out.println(orderNumber);
Проявил инициативу. Подумал, что будет лучше, если визуально будет видно какой номер получил заказ в рамках теста.
Удалил вывод номера заказа.

2022-09-30 09:54 UTC, teserstar commented on src/test/java/ru/yandex/practicum/pages/OrderPage.java
> +    private final By logoScooter = By.xpath(".//a[contains(@class, 'LogoScooter')]");
Моя ошибка. Удалил модификатор final из локаторов.

2022-09-30 09:55 UTC, teserstar commented on src/test/java/ru/yandex/practicum/tests/ContentOfAccordionQuestionsTest.java
> +        options.addArguments("--no-sandbox", "--headless", "--disable-dev-shm-usage");
Удалил дополнительные опции при запуске драйвера для тестов.

2022-09-30 09:57 UTC, teserstar commented on src/test/java/ru/yandex/practicum/tests/ContentOfAccordionQuestionsTest.java
> +    }
Удалил параметризацию из теста с проверкой "вопросов о важном". Добавил отдельный тест для каждого "вопроса".

2022-09-30 09:58 UTC, teserstar commented on src/test/java/ru/yandex/practicum/tests/CreatingScooterOrderTest.java
> +        };
Оставил параметризацию в тесте с оформлением заказа.

2022-10-02 11:14 UTC, pavel-ulan commented on src/test/java/ru/yandex/practicum/pages/OrderPage.java
> +        System.out.println(orderNumber);
Принято. задумка - хорошая, реализация спорная. Почему: как правило в проектах не делают вывод на системную консоль, т.к. системная консоль не видна. Если хочешь что бы что-то осталось в выводе используй логгеры, т.к. как правило логгеры используются на всех проектах, лог прогона прикрепляется к отчетам и т.п.

2022-10-02 11:16 UTC, pavel-ulan commented on src/test/java/ru/yandex/practicum/pages/OrderPage.java
> +    private final By logoScooter = By.xpath(".//a[contains(@class, 'LogoScooter')]");
не то, что бы это ошибка. в теории, можно и так делать. но как правило, локаторы, это просто приватные поля. делать их final без необходимости, наверное да, не стоит. но если это чем-то обосновано, то можно.

2022-10-02 11:34 UTC, pavel-ulan approved these changes
Хорошо 👍 
Будь повнимательнее, т.к. пару мест пропустил, которые надо было бы поправить. Ну и глянь комменты, я там тебе оставил пояснения по некоторым пунктам.

2022-10-02 11:34 UTC, pavel-ulan commented on src/test/java/ru/yandex/practicum/pages/StartPage.java
> +    private String eighthExpectedAnswer = "Да, обязательно. Всем самокатов! И Москве, и Московской области.";
Вот кстати в отличии от локаторов, тестовые данные (особенно строковые), обычно принято делать константами. Честно, я не помню почему (и я даже погуглил, но внятного ответа не нашел), но на всех моих проектах было так. 
Можешь кстати наставника пнуть, может он сможет дать ответ =)

2022-10-02 11:34 UTC, pavel-ulan commented on src/test/java/ru/yandex/practicum/tests/CreatingScooterOrderTest.java
> +    private final String date;
а тут забыл 🤔

2022-10-05 13:09 UTC, merged